### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by codyc1515** [aso824/yeehack#1]
Hi there, looks like the content is missing? I’m interested in any success that you had with this.

**Comment by aso824** [comment]
@codyc1515 just added :)

**Comment by codyc1515** [comment]
Legend. If I understood right you just need the BLE signing key and then you may unlock the device with this library? If yes, I will see if I can get this thing added into Home Assistant. It will be a great help.

**Comment by aso824** [comment]
@codyc1515 yes, everything explained in README - you can use this tool to fetch BLE sign key from Yeelock server and interact directly with lock using any device with BLE supported by kernel and underlying library - I bet that any adapter visible by `bluetoothctl` will work.

To integrate with HA, run server and use NodeRED to do things - in my case, I'm sending requests on switch helper state change.
